name: rubiii
description: no description
url: http://rubiii.com
permalink: date
pygments: true
exclude: ["config.rb", "Rakefile", "Gemfile", "Gemfile.lock"]
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
